### ISSUE TITLE
How to make a similar home page?

### ISSUE THREAD

**Issue by venkatesh71097** [jeya-maria-jose/jeya-maria-jose.github.io#1]
Hi there, 
I would be applying to MS and would want to make myself a similar website .
Can you give the resources. Thank You

**Comment by jeya-maria-jose** [comment]
Yeah , @venkatesh71097 .

When people can say they are know deep learning and are CUNTent Head , oh sorry Content*
, oh wait aspiring film journo too xD, 

but fail to know the difference between Convoluted and Convolutional .

My bad
